-- ============================================
-- Faculty Project Management Population Script (Idempotent)
-- - Fixed reserved variable names in function
-- - Idempotent: safely re-runnable (removes previously auto-generated data)
-- - Distinguishes auto-generated rows by using the domain: @autogen.udusok.edu.ng
-- ============================================

USE faculty_projects;

-- =================================================
-- 0. Clean up previous auto-generated data (idempotency)
-- =================================================
-- We identify our auto-generated rows by the unique email domain '@autogen.udusok.edu.ng'
-- and by project/title prefixes 'Auto Project' / 'Auto Topic' etc.

START TRANSACTION;

-- Remove bookings tied to auto-generated projects (if any)
DELETE b FROM bookings b
JOIN projects p ON b.project_id = p.id
WHERE p.title LIKE 'Auto Project %';

-- Remove auto-generated projects
DELETE FROM projects WHERE title LIKE 'Auto Project %';

-- Remove auto-generated proposed and approved topics
DELETE FROM proposed_topics WHERE title LIKE 'Auto Topic %';
DELETE FROM approved_topics WHERE title LIKE 'Auto Topic %';

-- Remove auto-generated users (students and coordinators we created previously)
DELETE FROM users WHERE email LIKE '%@autogen.udusok.edu.ng';

-- Remove previous coordinator_availability entries referencing removed users
DELETE ca FROM coordinator_availability ca
LEFT JOIN users u ON ca.coordinator_id = u.id
WHERE u.id IS NULL;

COMMIT;

-- =================================================
-- 1. FUNCTION: RANDOM NAME GENERATOR (safe variable names)
-- =================================================
DROP FUNCTION IF EXISTS random_name;
DELIMITER //
CREATE FUNCTION random_name() 
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
    DECLARE name_list TEXT;
    DECLARE total_names INT;
    DECLARE rand_index INT;

    SET name_list = 'Aisha,Bello,Fatima,Grace,Hauwa,Ibrahim,Musa,Sani,Usman,Zainab,John,Paul,Mary,Daniel,Joshua,Peace,Samuel,Ruth,Mark,David';
    SET total_names = 20;

    SET rand_index = FLOOR(1 + RAND() * total_names);

    RETURN SUBSTRING_INDEX(SUBSTRING_INDEX(name_list, ',', rand_index), ',', -1);
END //
DELIMITER ;

-- =================================================
-- 2. PROCEDURE: POPULATE COORDINATORS (idempotent)
-- =================================================
-- We'll insert coordinators using @autogen.udusok.edu.ng emails, so they can be removed on next run.
DROP PROCEDURE IF EXISTS populate_coordinators;
DELIMITER //
CREATE PROCEDURE populate_coordinators()
BEGIN
    -- Coordinators data: department_id map 1..5
    INSERT INTO users(full_name, email, phone_number, password, role, admission_no, department_id)
    SELECT * FROM (
        SELECT 'Dr. Aminu Bello' AS full_name, 'cs_coordinator@autogen.udusok.edu.ng' AS email, '08011111112' AS phone_number, 'coordinator123' AS password, 'coordinator' AS role, NULL AS admission_no, 1 AS department_id
        UNION ALL SELECT 'Dr. Fatima Sani','stats_coordinator@autogen.udusok.edu.ng','08022222223','coordinator123','coordinator',NULL,2
        UNION ALL SELECT 'Dr. Chinedu Eze','math_coordinator@autogen.udusok.edu.ng','08033333334','coordinator123','coordinator',NULL,3
        UNION ALL SELECT 'Dr. Grace Okoro','geo_coordinator@autogen.udusok.edu.ng','08044444445','coordinator123','coordinator',NULL,4
        UNION ALL SELECT 'Dr. Mohammed Ibrahim','physics_coordinator@autogen.udusok.edu.ng','08055555556','coordinator123','coordinator',NULL,5
    ) AS tmp
    WHERE NOT EXISTS (
        SELECT 1 FROM users u WHERE u.email = tmp.email
    );
END //
DELIMITER ;

-- =================================================
-- 3. PROCEDURE: POPULATE STUDENTS (150 per department) - idempotent
-- =================================================
DROP PROCEDURE IF EXISTS populate_students;
DELIMITER //
CREATE PROCEDURE populate_students()
BEGIN
    DECLARE dept INT;
    DECLARE prefix INT;
    DECLARE id_num INT;
    DECLARE full VARCHAR(200);
    DECLARE email VARCHAR(200);
    DECLARE phone VARCHAR(20);
    DECLARE admission_no VARCHAR(50);

    SET dept = 1;

    WHILE dept <= 5 DO
        IF dept = 1 THEN SET prefix = 1031;
        ELSEIF dept = 2 THEN SET prefix = 1032;
        ELSEIF dept = 3 THEN SET prefix = 1033;
        ELSEIF dept = 4 THEN SET prefix = 1034;
        ELSEIF dept = 5 THEN SET prefix = 1035;
        END IF;

        SET id_num = 1;
        WHILE id_num <= 150 DO
            SET full = CONCAT(random_name(), ' ', random_name());
            -- Use distinct domain so we can safely remove these autogenerated rows on reruns
            SET email = CONCAT(prefix, LPAD(id_num, 4, '0'), '@autogen.udusok.edu.ng');
            SET phone = CONCAT('080', LPAD(FLOOR(RAND()*9999999), 7, '0'));
            SET admission_no = CONCAT(prefix, LPAD(id_num, 4, '0'));

            -- Insert only if admission_no/email doesn't already exist
            IF NOT EXISTS (SELECT 1 FROM users WHERE admission_no = admission_no OR email = email) THEN
                INSERT INTO users(full_name, email, phone_number, password, role, admission_no, department_id)
                VALUES (full, email, phone, 'student123', 'student', admission_no, dept);
            END IF;

            SET id_num = id_num + 1;
        END WHILE;
        SET dept = dept + 1;
    END WHILE;
END //
DELIMITER ;

-- =================================================
-- 4. PROCEDURE: POPULATE PROJECTS (50 per department) - idempotent
-- =================================================
DROP PROCEDURE IF EXISTS populate_projects;
DELIMITER //
CREATE PROCEDURE populate_projects()
BEGIN
    DECLARE dept INT DEFAULT 1;
    DECLARE i INT;
    DECLARE stu_name VARCHAR(150);
    DECLARE proj_title VARCHAR(255);
    DECLARE sup_name VARCHAR(150);

    WHILE dept <= 5 DO
        SET i = 1;
        WHILE i <= 50 DO
            -- pick random student from department
            SELECT full_name INTO stu_name
            FROM users
            WHERE department_id = dept AND role='student' AND email LIKE '%@autogen.udusok.edu.ng'
            ORDER BY RAND() LIMIT 1;

            SET proj_title = CONCAT('Auto Project ', dept, '-', LPAD(i,3,'0'));
            SET sup_name = CONCAT('Dr. ', random_name());

            -- Insert project only if title not exists
            IF NOT EXISTS (SELECT 1 FROM projects WHERE title = proj_title) THEN
                INSERT INTO projects(title, student_name, supervisor_name, year_of_submission, availability_status, department_id)
                VALUES (proj_title, COALESCE(stu_name, CONCAT('Student Dept',dept)), sup_name, 2022 + FLOOR(RAND()*3), ELT(FLOOR(1+RAND()*3), 'available', 'borrowed', 'booked'), dept);
            END IF;

            SET i = i + 1;
        END WHILE;
        SET dept = dept + 1;
    END WHILE;
END //
DELIMITER ;

-- =================================================
-- 5. PROCEDURE: POPULATE BOOKINGS (200 mixed) - idempotent-ish
-- =================================================
DROP PROCEDURE IF EXISTS populate_bookings;
DELIMITER //
CREATE PROCEDURE populate_bookings()
BEGIN
    -- We'll only create bookings for projects with title prefix 'Auto Project'
    INSERT INTO bookings(project_id, student_id, booking_status, booked_at, expires_at)
    SELECT 
        p.id,
        u.id,
        ELT(FLOOR(1+RAND()*4), 'pending', 'collected', 'expired', 'returned'),
        NOW() - INTERVAL FLOOR(RAND()*30) DAY,
        NOW() + INTERVAL FLOOR(RAND()*3) DAY
    FROM projects p
    JOIN users u ON u.department_id = p.department_id AND u.role='student' AND u.email LIKE '%@autogen.udusok.edu.ng'
    WHERE p.title LIKE 'Auto Project %'
    ORDER BY RAND()
    LIMIT 200;
END //
DELIMITER ;

-- =================================================
-- 6. POPULATE PROPOSED TOPICS and APPROVED TOPICS (idempotent)
-- =================================================
-- Proposed topics
INSERT INTO proposed_topics(title, case_study, student_id, supervisor_name, problem_statement, topic_objectives, status, department_id)
SELECT 
    CONCAT('Auto Topic ', u.department_id, '-', u.id),
    'Faculty of Science',
    u.id,
    CONCAT('Dr. ', random_name()),
    'Autogenerated problem description.',
    'Autogenerated objectives.',
    ELT(FLOOR(1+RAND()*3), 'pending', 'approved', 'rejected'),
    u.department_id
FROM users u
WHERE u.role='student' AND u.email LIKE '%@autogen.udusok.edu.ng'
  AND NOT EXISTS (SELECT 1 FROM proposed_topics pt WHERE pt.title = CONCAT('Auto Topic ', u.department_id, '-', u.id))
LIMIT 150;

-- Approved topics (some of the proposed can be moved to approved for variety)
INSERT INTO approved_topics(title, case_study, student_id, supervisor_name, date_of_approval, department_id)
SELECT 
    CONCAT('Auto Topic ', u.department_id, '-', u.id),
    'Faculty of Science',
    u.id,
    CONCAT('Dr. ', random_name()),
    DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND()*300) DAY),
    u.department_id
FROM users u
WHERE u.role='student' AND u.email LIKE '%@autogen.udusok.edu.ng'
  AND NOT EXISTS (SELECT 1 FROM approved_topics at WHERE at.title = CONCAT('Auto Topic ', u.department_id, '-', u.id))
LIMIT 60;

-- =================================================
-- 7. SET COORDINATOR AVAILABILITY (idempotent)
-- =================================================
-- Map coordinator emails to departments and set availability
INSERT INTO coordinator_availability(coordinator_id, status)
SELECT u.id, ELT(FLOOR(1+RAND()*2), 'available', 'unavailable')
FROM users u
WHERE u.role = 'coordinator' AND u.email LIKE '%@autogen.udusok.edu.ng'
  AND NOT EXISTS (SELECT 1 FROM coordinator_availability ca WHERE ca.coordinator_id = u.id);

-- =================================================
-- 8. EXECUTION: CALL PROCEDURES
-- =================================================
CALL populate_coordinators();
CALL populate_students();
CALL populate_projects();
CALL populate_bookings();

-- =================================================
-- 9. SUMMARY CHECKS
-- =================================================
SELECT 'Users' AS TableName, COUNT(*) AS Total FROM users;
SELECT 'Auto-generated Users', COUNT(*) FROM users WHERE email LIKE '%@autogen.udusok.edu.ng';
SELECT 'Projects', COUNT(*) FROM projects;
SELECT 'Auto-generated Projects', COUNT(*) FROM projects WHERE title LIKE 'Auto Project %';
SELECT 'Bookings', COUNT(*) FROM bookings;
SELECT 'Proposed Topics', COUNT(*) FROM proposed_topics;
SELECT 'Approved Topics', COUNT(*) FROM approved_topics;

-- End of script